export const departments = ["Accident and emergency (A&E)",
    "Admissions",
    "Anesthetics",
    "Breast Screening",
    "Burn Center",
    "Cardiology",
    "Central Sterile Services Department (CSSD)",
    "Chaplaincy",
    "Coronary Care Unit (CCU)",
    "Critical Care",
    "Diagnostic Imaging",
    "Discharge Lounge",
    "Elderly services",
    "Finance Department",
    "Gastroenterology",
    "General Services",
    "General Surgery",
    "Gynecology",
    "Haematology",
    "Health & Safety",
    "Intensive Care Unit (ICU)",
    "Human Resources",
    "Infection Control",
    "Information Management",
    "Maternity",
    "Medical Records",
    "Microbiology",
    "Neonatal",
    "Nephrology",
    "Neurology",
    "Nutrition and Dietetics",
    "Obstetrics/Gynecology",
    "Occupational Therapy",
    "Oncology",
    "Ophthalmology",
    "Orthopaedics",
    "Otolaryngology (Ear, Nose, and Throat)",
    "Pain Management",
    "Patient Accounts",
    "Patient Services",
    "Pharmacy",
    "Physiotherapy",
    "Purchasing & Supplies",
    "Radiology",
    "Radiotherapy",
    "Renal",
    "Rheumatology",
    "Sexual Health",
    "Social Work",
    "Urology"];

export const doctorsSpeciality = ["Allergist",
    "Anaesthesiologist",
    "Andrologist",
    "Cardiologist",
    "Cardiac Electrophysiologist",
    "Dermatologist",
    "Emergency Room (ER) Doctors",
    "Endocrinologist",
    "Epidemiologist",
    "Family Medicine Physician",
    "Gastroenterologist",
    "Geriatrician",
    "Hyperbaric Physician",
    "Hematologist",
    "Hepatologist",
    "Immunologist",
    "Infectious Disease Specialist",
    "Intensivist",
    "Internal Medicine Specialist",
    "Maxillofacial Surgeon / Oral Surgeon",
    "Medical Examiner",
    "Medical Geneticist",
    "Neonatologist",
    "Nephrologist",
    "Neurologist",
    "Neurosurgeon",
    "Nuclear Medicine Specialist",
    "Obstetrician/Gynecologist (OB/GYN)",
    "Occupational Medicine Specialist",
    "Oncologist",
    "Ophthalmologist",
    "Orthopedic Surgeon / Orthopedist",
    "Otolaryngologist (also ENT Specialist)",
    "Parasitologist",
    "Pathologist",
    "Perinatologist",
    "Periodontist",
    "Pediatrician",
    "Physiatrist",
    "Plastic Surgeon",
    "Psychiatrist",
    "Pulmonologist",
    "Radiologist",
    "Rheumatologist",
    "Sleep Doctor / Sleep Disorders Specialist",
    "Spinal Cord Injury Specialist",
    "Sports Medicine Specialist",
    "Surgeon",
    "Thoracic Surgeon",
    "Urologist",
    "Vascular Surgeon",
    "Veterinarian",
    "Palliative Care Specialist",
    "Acupuncturist",
    "Audiologist",
    "Ayurvedic Practioner",
    "Chiropractor",
    "Diagnostician",
    "Homeopathic Doctor",
    "Microbiologist",
    "Naturopathic Doctor",
    "Pharmacist",
    "Physiotherapist",
    "Podiatrist / Chiropodist",
    "Registered Massage Therapist"];

export const qualifications = ["MS", "MD", "MBBS"];
